language: php

sudo: false

php:
  - 5.4
  - 5.5

install:
  - travis_retry composer install --no-interaction --no-ansi --no-progress --no-suggest --prefer-source

script:
  - phpunit -c phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
